# Generated by Django 5.1.4 on 2025-11-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ToDo', 'ToDo'), ('Done', 'Done')], default='ToDo', max_length=10)),
                ('todo_id', models.IntegerField(db_index=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.BigIntegerField()),
                ('updated_at', models.BigIntegerField()),
                ('completed_at', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subtasks',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['todo_id', 'status'], name='subtasks_todo_id_37e777_idx'), models.Index(fields=['todo_id', 'order'], name='subtasks_todo_id_dc6d32_idx')],
            },
        ),
    ]
