# Generated by Django 5.1.4 on 2025-11-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_private', models.BooleanField(default=True)),
                ('owner_id', models.IntegerField(db_index=True)),
                ('created_at', models.BigIntegerField()),
                ('updated_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner_id', 'is_private'], name='projects_owner_i_8d3c8a_idx'), models.Index(fields=['owner_id', 'created_at'], name='projects_owner_i_eab97e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(db_index=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('role', models.CharField(choices=[('Owner', 'Owner'), ('Admin', 'Admin'), ('Member', 'Member')], default='Member', max_length=10)),
                ('joined_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'project_members',
                'indexes': [models.Index(fields=['project_id', 'role'], name='project_mem_project_0d0b7d_idx'), models.Index(fields=['user_id', 'role'], name='project_mem_user_id_b5a231_idx')],
                'unique_together': {('project_id', 'user_id')},
            },
        ),
    ]
