# Generated by Django 5.1.4 on 2025-11-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('filter_criteria', models.JSONField(default=dict)),
                ('user_id', models.IntegerField(db_index=True)),
                ('created_at', models.BigIntegerField()),
                ('updated_at', models.BigIntegerField()),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'saved_filters',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'is_default'], name='saved_filte_user_id_74525f_idx'), models.Index(fields=['user_id', 'created_at'], name='saved_filte_user_id_2a113b_idx')],
            },
        ),
    ]
