# Generated by Django 5.1.4 on 2025-11-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status_value', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, default='#6B7280', max_length=20)),
                ('project_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.BigIntegerField()),
                ('updated_at', models.BigIntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'kanban_columns',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['project_id', 'is_active'], name='kanban_colu_project_03d962_idx'), models.Index(fields=['user_id', 'is_active'], name='kanban_colu_user_id_889299_idx'), models.Index(fields=['project_id', 'order'], name='kanban_colu_project_a9cc93_idx')],
            },
        ),
    ]
