# Generated by Django 5.1.4 on 2025-11-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('deadline', models.BigIntegerField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=10)),
                ('status', models.CharField(choices=[('ToDo', 'ToDo'), ('In Progress', 'In Progress'), ('Waiting', 'Waiting'), ('Blocked', 'Blocked'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], default='ToDo', max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('user_id', models.IntegerField(db_index=True)),
                ('project_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('previous_todo_id', models.IntegerField(blank=True, null=True)),
                ('next_todo_id', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.BigIntegerField()),
                ('updated_at', models.BigIntegerField()),
                ('completed_at', models.BigIntegerField(blank=True, null=True)),
                ('auto_repeat', models.CharField(choices=[('None', 'None'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='None', max_length=10)),
            ],
            options={
                'db_table': 'todos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'status'], name='todos_user_id_df25ca_idx'), models.Index(fields=['user_id', 'deadline'], name='todos_user_id_1254ab_idx'), models.Index(fields=['project_id', 'status'], name='todos_project_b70e3f_idx'), models.Index(fields=['user_id', 'created_at'], name='todos_user_id_8f2d9c_idx')],
            },
        ),
    ]
