# Generated by Django 5.1.4 on 2025-11-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('reminder_time', models.BigIntegerField()),
                ('sent_at', models.BigIntegerField(blank=True, null=True)),
                ('notification_channels', models.JSONField(default=list)),
                ('todo_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('reminder_type', models.CharField(choices=[('Manual', 'Manual'), ('Deadline_Proximity', 'Deadline Proximity'), ('Overdue', 'Overdue'), ('Smart', 'Smart')], default='Manual', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.BigIntegerField()),
                ('updated_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'reminders',
                'ordering': ['reminder_time'],
                'indexes': [models.Index(fields=['user_id', 'status'], name='reminders_user_id_5f8b60_idx'), models.Index(fields=['reminder_time', 'status'], name='reminders_reminde_93c477_idx'), models.Index(fields=['todo_id', 'status'], name='reminders_todo_id_710463_idx'), models.Index(fields=['user_id', 'reminder_time'], name='reminders_user_id_b9d37f_idx')],
            },
        ),
    ]
